spring:
  application:
    name: test-one-hundred-rows-find-all
  datasource:
    url: jdbc:postgresql://localhost:5432/test_one_hundred_rows_find_all
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true